name: Publish presentation
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      presentation_dir: presentation/reformatoncopy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: yarn
          cache-dependency-path: ${{ env.presentation_dir }}/yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ${{ env.presentation_dir }}
      - name: Build
        run: yarn run build --base=/ReformatOnCopy/
        working-directory: ${{ env.presentation_dir }}
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: ${{ env.presentation_dir }}/dist
          jekyll: false
          target_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
