name: Publish presentation
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: yarn
          cache-dependency-path: presentation/reformatoncopy/yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: &presentation-dir presentation/reformatoncopy
      - name: Build
        run: yarn run build
        working-directory: *presentation-dir
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: presentation/reformatoncopy/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
